#include "stm32f4xx.h"
#include "ltdc_cfg.h"
#include "gpio_cfg.h"
#include "sdram_cfg.h"

void LTDC_IO_Init(void)
{
    // GPIO pin configuration
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN | RCC_AHB1ENR_GPIODEN | RCC_AHB1ENR_GPIOFEN | RCC_AHB1ENR_GPIOGEN;

    Pin_Cfg(GPIOC, 10, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_R2
    Pin_Cfg(GPIOB,  0, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE,  AF_9);    // LCD_R3
    Pin_Cfg(GPIOA, 11, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_R4
    Pin_Cfg(GPIOA, 12, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_R5
    Pin_Cfg(GPIOB,  1, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE,  AF_9);    // LCD_R6
    Pin_Cfg(GPIOG,  6, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_R7
    Pin_Cfg(GPIOA,  6, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_G2
    Pin_Cfg(GPIOG, 10, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE,  AF_9);    // LCD_G3
    Pin_Cfg(GPIOB, 10, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_G4
    Pin_Cfg(GPIOB, 11, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_G5
    Pin_Cfg(GPIOC,  7, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_G6
    Pin_Cfg(GPIOD,  3, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_G7
    Pin_Cfg(GPIOD,  6, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_B2
    Pin_Cfg(GPIOG, 11, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_B3
    Pin_Cfg(GPIOG, 12, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE,  AF_9);    // LCD_B4
    Pin_Cfg(GPIOA,  3, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_B5
    Pin_Cfg(GPIOB,  8, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_B6
    Pin_Cfg(GPIOB,  9, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_B7
    Pin_Cfg(GPIOA,  4, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_VSYNC
    Pin_Cfg(GPIOC,  6, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_HSYNC
    Pin_Cfg(GPIOF, 10, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_DE
    Pin_Cfg(GPIOG,  7, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_14);    // LCD_CLK
}

void LTDC_Core_Init(void)
{
    // Enable clock for LTDC
    RCC->APB2ENR |= RCC_APB2ENR_LTDCEN;

    // Synchronization Size
    LTDC->SSCR = ((HSYNC - 1) << LTDC_SSCR_HSW_Pos) | (VSYNC - 1);
    // Back Porch Configuration
    LTDC->BPCR = (((HSYNC + HBP) - 1) << LTDC_BPCR_AHBP_Pos) | ((VSYNC + VBP) - 1);
    // Active Width Configuration
    LTDC->AWCR = (((HSYNC + HBP + LCD_ACTIVE_WIDTH) - 1) << LTDC_AWCR_AAW_Pos) | ((VSYNC + VBP + LCD_ACTIVE_HEIGHT) - 1);
    // Total Width Configuration
    LTDC->TWCR = (((HSYNC + HBP + LCD_ACTIVE_WIDTH + HFP) - 1) << LTDC_TWCR_TOTALW_Pos) | ((VSYNC + VBP + LCD_ACTIVE_HEIGHT + VFP) - 1);

    // Window Horizontal Position Configuration
    LTDC_Layer1->WHPCR = (((HSYNC + HBP + LCD_ACTIVE_WIDTH) - 1) << LTDC_LxWHPCR_WHSPPOS_Pos) | (((HSYNC + HBP) - 1) + 1);
    // Window Vertical Position Configuration 
    LTDC_Layer1->WVPCR = (((VSYNC + VBP + LCD_ACTIVE_HEIGHT) - 1) << LTDC_LxWVPCR_WVSPPOS_Pos) | (((VSYNC + VBP) - 1) + 1);
    // Pixel Format Configuration RGB565
    LTDC_Layer1->PFCR = 2;
    // Color Frame Buffer Address
    LTDC_Layer1->CFBAR = SDRAM_BASE;
    // Color Frame Buffer Length
    LTDC_Layer1->CFBLR  = ((LCD_ACTIVE_WIDTH * PIXEL_WIDHT) << LTDC_LxCFBLR_CFBP_Pos) | ((LCD_ACTIVE_WIDTH * PIXEL_WIDHT) + 3);
    // ColorFrame Buffer Line Numbe
    LTDC_Layer1->CFBLNR = LCD_ACTIVE_HEIGHT;
    // Enable Layer
    LTDC_Layer1->CR |= LTDC_LxCR_LEN;
    // Immediate Reload
    LTDC->SRCR = LTDC_SRCR_IMR;

    // Enable LTDC
    LTDC->GCR = LTDC_GCR_LTDCEN;
}
