#include "stm32f4xx.h"
#include "gpio_cfg.h"
#include "sdram_cfg.h"
#include "delay.h"

//*********************************************************//
//********* Settings for IS42S16400J-7TL ******************//
//*********************************************************//

// SDRAM device timings
#define TMRD    2
#define TXSR    7
#define TRAS    4
#define TRC     7
#define TWR     2
#define TRP     2
#define TRCD    2

// Auto-Refresh cycles
#define CMR_NRFS     2 //5

// Mode Register (MRD field in FMC_SDCMR)
#define MRD_BURST_LENGTH        (1 << 0)    // MRD[2:0], Burst Length = 2
#define MRD_BURST_TYPE          (0 << 3)    // MRD[3], 0 - Sequential, 1 - Interleaved
#define MRD_LATENCY_MODE        (3 << 4)    // MRD[6:4], CAS Latency = 3
#define MRD_OP_MODE             (0 << 7)    // MRD[8:7]
#define MRD_WRITE_BURST_MODE    (1 << 9)    // MRD[9], 0 - Programmed Burst Length, 1 - Single Location Access
#define MRD_VAL                 (MRD_WRITE_BURST_MODE | MRD_OP_MODE | MRD_LATENCY_MODE | MRD_BURST_TYPE | MRD_BURST_LENGTH)
// Refresh Rate
#define RTR_COUNT   (1386 & ~(0x1FFF))      // ((64ms / 4096) * 90MHz) - 20

//*********************************************************//

void SDRAM_IO_Init(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN | RCC_AHB1ENR_GPIODEN | RCC_AHB1ENR_GPIOEEN | RCC_AHB1ENR_GPIOFEN | RCC_AHB1ENR_GPIOGEN;

    Pin_Cfg(GPIOF,  0, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A0
    Pin_Cfg(GPIOF,  1, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A1
    Pin_Cfg(GPIOF,  2, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A2
    Pin_Cfg(GPIOF,  3, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A3
    Pin_Cfg(GPIOF,  4, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A4
    Pin_Cfg(GPIOF,  5, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A5
    Pin_Cfg(GPIOF, 12, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A6
    Pin_Cfg(GPIOF, 13, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A7
    Pin_Cfg(GPIOF, 14, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A8
    Pin_Cfg(GPIOF, 15, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A9
    Pin_Cfg(GPIOG,  0, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A10
    Pin_Cfg(GPIOG,  1, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_A11
    Pin_Cfg(GPIOD, 14, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D0
    Pin_Cfg(GPIOD, 15, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D1
    Pin_Cfg(GPIOD,  0, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D2
    Pin_Cfg(GPIOD,  1, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D3
    Pin_Cfg(GPIOE,  7, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D4
    Pin_Cfg(GPIOE,  8, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D5
    Pin_Cfg(GPIOE,  9, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D6
    Pin_Cfg(GPIOE, 10, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D7
    Pin_Cfg(GPIOE, 11, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D8
    Pin_Cfg(GPIOE, 12, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D9
    Pin_Cfg(GPIOE, 13, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D10
    Pin_Cfg(GPIOE, 14, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D11
    Pin_Cfg(GPIOE, 15, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D12
    Pin_Cfg(GPIOD,  8, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D13
    Pin_Cfg(GPIOD,  9, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D14
    Pin_Cfg(GPIOD, 10, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_D15
    Pin_Cfg(GPIOB,  5, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_SDCKE1
    Pin_Cfg(GPIOB,  6, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_SDNE1
    Pin_Cfg(GPIOC,  0, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_SDNWE
    Pin_Cfg(GPIOE,  0, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_NBL0
    Pin_Cfg(GPIOE,  1, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_NBL1
    Pin_Cfg(GPIOF, 11, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_SDNRAS
    Pin_Cfg(GPIOG,  4, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_BA0
    Pin_Cfg(GPIOG,  5, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_BA1
    Pin_Cfg(GPIOG,  8, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_SDCLK
    Pin_Cfg(GPIOG, 15, MODER_AF, OTYPER_PP, OSPEEDR_VERY_HIGH, PUPDR_PULL_NONE, AF_12);    // SDRAM_SDNCAS
}

void SDRAM_Init(void)
{
	RCC->AHB3ENR |= RCC_AHB3ENR_FMCEN;	
	// SDRAM features
    FMC_Bank5_6->SDCR[0] = FMC_SDCR1_RPIPE_1 | FMC_SDCR1_RBURST | FMC_SDCR1_SDCLK_1;
	FMC_Bank5_6->SDCR[1] = FMC_SDCR1_CAS | FMC_SDCR1_NB | FMC_SDCR1_MWID_0 | FMC_SDCR1_NR_0;
	// Set timings
    FMC_Bank5_6->SDTR[0] = (TRP << FMC_SDTR1_TRP_Pos) | (TRC << FMC_SDTR1_TRC_Pos);
    FMC_Bank5_6->SDTR[1] = (TRCD << FMC_SDTR2_TRCD_Pos) | (TWR << FMC_SDTR2_TWR_Pos) | (TRAS << FMC_SDTR2_TRAS_Pos) | (TXSR << FMC_SDTR2_TXSR_Pos) | (TMRD << FMC_SDTR2_TMRD_Pos);
    // Clock Configuration Enable
	while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY){};
    FMC_Bank5_6->SDCMR = FMC_SDCMR_CTB2 | FMC_SDCMR_MODE_0;
	// Wait 
	delay_ms(1);
    // PALL (“All Bank Precharge”) command
	while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY){};
	FMC_Bank5_6->SDCMR = FMC_SDCMR_CTB2 | FMC_SDCMR_MODE_1;
	// Auto-refresh command
	while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY){};
	FMC_Bank5_6->SDCMR = FMC_SDCMR_CTB2 | ((CMR_NRFS-1) << FMC_SDCMR_NRFS_Pos) | FMC_SDCMR_MODE_1 | FMC_SDCMR_MODE_0;	
	// Load Mode Register
	while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY){};
	FMC_Bank5_6->SDCMR = (MRD_VAL << FMC_SDCMR_MRD_Pos) | FMC_SDCMR_CTB2 | FMC_SDCMR_MODE_2;
	// Refresh Rate
	while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY){};
	FMC_Bank5_6->SDRTR = (RTR_COUNT << FMC_SDRTR_COUNT_Pos);
    while(FMC_Bank5_6->SDSR & FMC_SDSR_BUSY){};
	// Clear SDRAM
    for(uint32_t ptr = SDRAM_BASE; ptr < (SDRAM_BASE + SDRAM_SIZE); ptr += 4)
	{
        *((uint32_t *)ptr) = 0xFFFFFFFF;
	}
}

